### ISSUE TITLE
qt theme with qupzilla

### ISSUE THREAD

**Issue by th1rd** [mati75/qt5ct#1]
Debian jessie, qt 5.3.2 qupzilla 1.8.9. qt theme qtcurve set by qt5ct (QT_QPA_PLATFORMTHEME="qt5ct").

Whe qupzilla starts I see problems with drawing some GUI elements. Main menu, address bar, search bar and add empry tab button.

![1](https://cloud.githubusercontent.com/assets/17023663/13526059/77453876-e216-11e5-9691-25b36d7c0608.png)

qupzilla discussion: [https://github.com/QupZilla/qupzilla/issues/1875](https://github.com/QupZilla/qupzilla/issues/1875)

**Comment by mati75** [comment]
I'm not a qt5ct developer. This repository is only for Debian packaging. 

Please report here: https://sourceforge.net/p/qt5ct/tickets/?source=navbar
