### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by kevingnet** [mati75/qt5ct#3]
cd src/qt5ct-qtplugin/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /usr/src/qt5ct/qt5ct-master/src/qt5ct-qtplugin/qt5ct-qtplugin.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/usr/src/qt5ct/qt5ct-master/src/qt5ct-qtplugin'
make[1]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libQt5PlatformSupport.a', needed by 'libqt5ct.so'.  Stop.
make[1]: Leaving directory '/usr/src/qt5ct/qt5ct-master/src/qt5ct-qtplugin'
Makefile:44: recipe for target 'sub-src-qt5ct-qtplugin-make_first' failed
make: *** [sub-src-qt5ct-qtplugin-make_first] Error 2

I'm on linux mint 18

**Comment by mati75** [comment]
Package qtbase5-private-dev is missing. Try to install it.
