### ISSUE TITLE
enable by default

### ISSUE THREAD

**Issue by sixsixfive** [mati75/qt5ct#7]
like gtk3 nocsd this should be enabled by default if installed so please add something like:

```
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_PLATFORMTHEME=qt5ct
export QT_PLATFORM_PLUGIN=qt5ct
```

to  /etc/X11/Xsession.d/99-qt5ct.

**Comment by mati75** [comment]
Thanks. Added.
