### ISSUE TITLE
qt5ct wont install on linuxmint-18.2-cinnamon when base system install is from lm-18.2-kde

### ISSUE THREAD

**Issue by two-dogs** [mati75/qt5ct#9]
see gist pls first,
https://gist.github.com/anonymous/8e0987d381a74a4c72210ca437d56d61

the initial system install was from lm-18.2-kde which added the kubuntu ppa as shown on gist,  and then cinnamon was installed after, best i can tell the qt5ct package is not accounting for the existance of the possibility of updates to deps from other than xenial default repos, the kubuntu ppa added a fix to the base dep needed by qt5ct as shown on gist, pls allow for kubuntu ppa in the deps and issue resolved i would think, yes?

**Comment by two-dogs** [comment]
https://sourceforge.net/projects/qt5ct/
https://launchpad.net/~hda-me/+archive/ubuntu/qt5ct
https://github.com/mati75/qt5ct

**Comment by mati75** [comment]
kubuntu-ppa broke depends, however: https://launchpad.net/%7Ehda-me/+archive/ubuntu/qt5ct this is not mine ppa

**Comment by two-dogs** [comment]
@mati75 , my bad, found your ppa, https://launchpad.net/~mati75/+archive/ubuntu/qt5ct

**Comment by two-dogs** [comment]
@mati75  your ppa install of qt5ct also breaks if http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu is active, same dep errors as discussed above, i'll resubmit issue

**Comment by mati75** [comment]
Try to install package for ubuntu 16.10 from my ppa.

**Comment by two-dogs** [comment]
@mati75 will try thanks
